core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', include('core.urls', namespace='core')),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('new-user/', views.register, name='new-user'),
    path('new-company/', views.newCompany, name='new-company'),
    path('users/', views.usersView, name='users'),
    path('users/profile', views.profile, name='profile'),
    path('users/<int:profile_id>/', views.user_view, name='user'),
    path('users/invite/<int:profile_id>/', views.invite, name='invite'),
    path('users/invites/', views.invites, name='invites'),
    path('users/invites/accept/<int:invite_id>/', views.acceptInvite, name='accept-invite'),
    path('users/invites/delete/<int:invite_id>/', views.deleteInvite, name='delete-invite'),
    path('users/friends/', views.friends, name='friends'),
    path('users/friends/remove/<int:profile_id>/', views.remove_friend, name='remove-friend'),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


status = (
    ('1', 'Stuck'),
    ('2', 'Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField('shortcut', blank=True)
    assign = models.ManyToManyField(User)
    efforts = models.DurationField()
    status = models.CharField(max_length=7, choices=status, default=1)
    dead_line = models.DateField()
    company = models.ForeignKey('register.Company', on_delete=models.CASCADE)
    complete_per = models.FloatField(max_length=2, validators = [MinValueValidator(0), MaxValueValidator(100)])
    description = models.TextField(blank=True)

    add_date = models.DateField(auto_now_add=True)
    upd_date = models.DateField(auto_now_add=False, auto_now=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return (self.name)


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    assign = models.ManyToManyField(User)
    task_name = models.CharField(max_length=80)
    status = models.CharField(max_length=7, choices=status, default=1)
    due = models.CharField(max_length=7, choices=due, default=1)

    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        return(self.task_name)

register/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project

# Create your models here.
class Company(models.Model):
    social_name = models.CharField(max_length=80)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    city = models.CharField(max_length=50)
    found_date = models.DateField()

    class Meta:
        verbose_name_plural = 'Companies'
        ordering = ('name',)


    def __str__(self):
        return (self.name)

class UserProfile(models.Model):
    user    = models.ForeignKey(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    project = models.ManyToManyField(Project, blank=True)
    friends = models.ManyToManyField('self', blank=True)
    img    = models.ImageField(upload_to='core/avatar', blank=True, default='core/avatar/blank_profile.png')

    def __str__(self):
        return (str(self.user))

    def invite(self, invite_profile):
        invite = Invite(inviter=self, invited=invite_profile)
        invites = invite_profile.received_invites.filter(inviter_id=self.id)
        if not len(invites) > 0:    # don't accept duplicated invites
            invite.save()

    def remove_friend(self, profile_id):
        friend = UserProfile.objects.filter(id=profile_id)[0]
        self.friends.remove(friend)



class Invite(models.Model):
    inviter = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='made_invites')
    invited = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='received_invites')

    def accept(self):
        self.invited.friends.add(self.inviter)
        self.inviter.friends.add(self.invited)
        self.delete()

    def __str__(self):
        return str(self.inviter)

register/forms.py
from django import forms
from register.models import Company as Comp
from register.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(label='E-mail', required=True)
    company = forms.ModelChoiceField(queryset=Comp.objects.all())

    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'company',
            'password1',
            'password2',
        }

        labels = {
            'first_name': 'Name',
            'last_name': 'Last Name',
            'company': 'Company',
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        company = self.cleaned_data['company']

        if commit:
            user.save()
            user_profile = UserProfile.objects.create(user=user, company=Comp.objects.get(name=company))
            user_profile.save()

        return user

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'E-mail'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Retype Password'
        self.fields['company'].widget.attrs['class'] = 'form-control'


class CompanyRegistrationForm(forms.Form):
    social_name = forms.CharField(max_length=80)
    name = forms.CharField(max_length=80)
    email = forms.EmailField()
    city = forms.CharField(max_length=50)
    found_date = forms.DateField()

    class Meta:
        model = Comp


    def save(self, commit=True):
        company = Comp()
        company.social_name = self.cleaned_data['social_name']
        company.name = self.cleaned_data['name']
        company.email = self.cleaned_data['email']
        company.city = self.cleaned_data['city']
        company.found_date = self.cleaned_data['found_date']

        if commit:
            company.save()


    def __init__(self, *args, **kwargs):
        super(CompanyRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['social_name'].widget.attrs['class'] = 'form-control'
        self.fields['social_name'].widget.attrs['placeholder'] = 'Social Name'
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'Name'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['city'].widget.attrs['class'] = 'form-control'
        self.fields['city'].widget.attrs['placeholder'] = 'City'
        self.fields['found_date'].widget.attrs['class'] = 'form-control'
        self.fields['found_date'].widget.attrs['placeholder'] = 'Found date'


class ProfilePictureForm(forms.Form):
    img = forms.ImageField()
    class Meta:
        model = UserProfile
        fields = ['img']

    def save(self, request, commit=True):
        user = request.user.userprofile_set.first()
        user.img = self.cleaned_data['img']

        if commit:
            user.save()

        return user

    def __init__(self, *args, **kwargs):
        super(ProfilePictureForm, self).__init__(*args, **kwargs)
        self.fields['img'].widget.attrs['class'] = 'custom-file-input'
        self.fields['img'].widget.attrs['id'] = 'validatedCustomFile'

register/views.py
from django.shortcuts import render
from django.contrib.auth import login
from django.shortcuts import redirect
from projects.models import Task
from .models import UserProfile
from .models import Invite
from .forms import RegistrationForm
from .forms import CompanyRegistrationForm
from .forms import ProfilePictureForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            user = form.save()
            created = True
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            context = {'created' : created}
            return render(request, 'register/reg_form.html', context)
        else:
            return render(request, 'register/reg_form.html', context)
    else:
        form = RegistrationForm()
        context = {
            'form' : form,
        }
        return render(request, 'register/reg_form.html', context)


def usersView(request):
    users = UserProfile.objects.all()
    tasks = Task.objects.all()
    context = {
        'users': users,
        'tasks': tasks,
    }
    return render(request, 'register/users.html', context)

def user_view(request, profile_id):
    user = UserProfile.objects.get(id=profile_id)
    context = {
        'user_view' : user,
    }
    return render(request, 'register/user.html', context)


def profile(request):
    if request.method == 'POST':
        img_form = ProfilePictureForm(request.POST, request.FILES)
        print('PRINT 1: ', img_form)
        context = {'img_form' : img_form }
        if img_form.is_valid():
            img_form.save(request)
            updated = True
            context = {'img_form' : img_form, 'updated' : updated }
            return render(request, 'register/profile.html', context)
        else:
            return render(request, 'register/profile.html', context)
    else:
        img_form = ProfilePictureForm()
        context = {'img_form' : img_form }
        return render(request, 'register/profile.html', context)


def newCompany(request):
    if request.method == 'POST':
        form = CompanyRegistrationForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            form.save()
            created = True
            form = CompanyRegistrationForm()
            context = {
                'created' : created,
                'form' : form,
                       }
            return render(request, 'register/new_company.html', context)
        else:
            return render(request, 'register/new_company.html', context)
    else:
        form = CompanyRegistrationForm()
        context = {
            'form' : form,
        }
        return render(request, 'register/new_company.html', context)


def invites(request):
    return render(request, 'register/invites.html')


def invite(request, profile_id):
    profile_to_invite = UserProfile.objects.get(id=profile_id)
    logged_profile = get_active_profile(request)
    if not profile_to_invite in logged_profile.friends.all():
        logged_profile.invite(profile_to_invite)
    return redirect('core:index')


def deleteInvite(request, invite_id):
    logged_user = get_active_profile(request)
    logged_user.received_invites.get(id=invite_id).delete()
    return render(request, 'register/invites.html')


def acceptInvite(request, invite_id):
    invite = Invite.objects.get(id=invite_id)
    invite.accept()
    return redirect('register:invites')

def remove_friend(request, profile_id):
    user = get_active_profile(request)
    user.remove_friend(profile_id)
    return redirect('register:friends')


def get_active_profile(request):
    user_id = request.user.userprofile_set.values_list()[0][0]
    return UserProfile.objects.get(id=user_id)


def friends(request):
    if request.user.is_authenticated:
        user = get_active_profile(request)
        friends = user.friends.all()
        context = {
            'friends' : friends,
        }
    else:
        users_prof = UserProfile.objects.all()
        context= {
            'users_prof' : users_prof,
        }
    return render(request, 'register/friends.html', context)

register/templates/register/friends.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Friends</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
        <div class="row">
                {% if friends %}
                {% for friend in friends %}
                <div class="col-sm-6 col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="tab-pane p-3 active show">
                              <div class="message">
                                <div class="py-3 pb-5 mr-3 float-left">
                                  <div class="avatar">
                                    <img src="{{ friend.img.url }}" class="img-avatar" alt="{{ friend.user.get_full_name }}">
                                    <span class="avatar-status badge-success"></span>
                                  </div>
                                </div>
                                <div>
                                    <a href="{% url 'register:user' profile_id=friend.id %}"><small class="text-muted">{{ friend.user.get_full_name }}</small></a>
                                    {% if friend.user.last_login %}
                                  <small class="text-muted float-right mt-1">Last login: {{ friend.user.last_login|date:"H:i" }} in {{ friend.user.last_login|date:"d/m" }}</small>
                                    {% endif %}
                                </div>
                                <div class="text-truncate font-weight-bold">{{ friend.company }}</div>
                                {% if friend.user.project_set.all %}
                                <em class="text-muted">Projects that {{ friend.user.first_name }} is working:</em>
                                <small class="text-muted">
                                    {% for project in friend.user.project_set.all %}
                                    {{ project.name }},
                                    {% endfor %}
                                </small>
                                {% else %}
                                <em class="text-muted">{{ friend.user.first_name }} is working in no projects until now.</em>
                                {% endif %}
                                <div>
                                    <a href="{% url 'register:remove-friend' profile_id=friend.id %}" class="badge badge-danger text-white">Remove friend</a>
                                </div>
                              </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                {% if user.is_authenticated %}
                    <h3 class="m-5">You have no friends :(</h3>
                {% else %}
                    <a href="{% url 'core:login' %}" class="nav-link display-4">Log in to see your friends</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

register/templates/register/invites.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Invites</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
  <div id="ui-view" style="opacity: 1;"><div class="animated fadeIn">
    <div class="row">
    <div class="col-12">
        <div class="row">
            {% if logged_user.received_invites.count %}
            <!--<h3 class="lead">You have {{ logged_user.received_invites.count }} invite{{ logged_user.received_invites.count|pluralize }}.</h3>-->
            <table class="table table-responsive-sm table-hover table-outline mb-5 ">
                <thead class="thead-light">
                <tr>
                    <th class="text-center"><i class="fa fa-user"></i></th>
                    <th>User</th>
                    <th>Add / Delete</th>
                    <th>Company</th>
                    <th class="text-center">Friends*</th>
                    <th>Activity</th>
                </tr>
            </thead>
                    <tbody>
                        <!-- user -->
                        {% for invite in logged_user.received_invites.all %}
                        <tr>
                            <td class="text-center">
                                <div class="avatar">
                                <img src="{{ invite.inviter.img.url }}" class="img-avatar" alt="{{ user.email }}">
                                <span class="avatar-status badge-success"></span>
                                </div>
                            </td>
                            <td>
                                {% if invite.inviter.user.get_full_name %}
                                <div>{{ invite.inviter.user.get_full_name }}{% if invite.inviter.user.is_staff %} <span class="badge badge-pill badge-dark"> staff</span> {% endif %}</div>
                                {% else %}
                                <div>{{ invite.inviter.user.username }}{% if invite.inviter.user.is_staff %} <span class="badge badge-pill badge-dark"> staff</span> {% endif %}</div>
                                {% endif %}
                                <div class="small text-muted">
                                <span>Joined:</span> | {{ invite.inviter.user.date_joined }}
                                </div>
                            </td>
                            <td>
                                <a href="{% url 'register:accept-invite' invite_id=invite.id %}" class="badge badge-success text-white">Add friend</a>
                                <a href="{% url 'register:delete-invite' invite_id=invite.id %}" class="badge badge-danger text-white">Remove invite</a>
                            </td>
                            <td>
                                {{ invite.inviter.company }}
                            </td>
                            <td class="text-center">
                                <span class="badge badge-pill badge-dark">{{ invite.inviter.user.task_set.values.count }} ***</span>
                                <span class="badge badge-pill badge-dark"></span>
                            </td>
                            <td>
                                <div class="small text-muted">Last login</div>
                                <strong>{{ invite.inviter.user.last_login }}</strong>
                            </td>
                        </tr>
                        {% endfor %}
                        <!-- end user -->
                    </tbody>
                </table>
                {% else %}
                {% if user.is_authenticated %}
                    <h3 class="m-5">You have no invites :(</h3>
                {% else %}
                    <a href="{% url 'core:login' %}" class="nav-link display-4">Log in to see your invites</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    </div>
    </div>
  </div>
</div>
{% endblock %}

register/templates/register/user.html
{% extends 'core/base.html' %}
{% load staticfiles %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Users</li>
        <li class="breadcrumb-item active">Friends</li>
{% endblock breadcrumb%}

{% block content %}

<div class="container-fluid">
    <div id="ui-view" style="opacity: 1;">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-12 mb-3">
                    <div class="social-box" style="height:110%">
                        <img src="{{ user_view.img.url }}" class="img-avatar m-4" alt="{{ user_view }}" width="20%">
                        <ul>
                        <li>
                            <strong>{{ user_view.friends.all.count }}</strong>
                            <span>friends</span>
                        </li>
                        <li>
                            <strong>{{ user_view.project.all.count }}</strong>
                            <span>projects</span>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card mt-5">
                        <div class="simple-box">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    <ul class="mt-4 mx-5">
                                        <h5>Personal info:</h5>
                                        <li><span>Name:</span> {{ user_view.user.get_full_name }}</li>
                                        <li><span>Company:</span> {{ user_view.company }}</li>
                                        <li><span>E-mail:</span> {{ user_view.user.email}}</li>
                                        <li><span>Last login:</span> {{ user_view.user.last_login }}</li>
                                        <li><span>Date joined:</span> {{ user_view.user.date_joined }}</li>
                                    </ul>
                                </div>
                                <div class="col-12 col-md-6 text-left">
                                    <ul class="m-4">
                                        <h5>Tasks that {{ user_view.user.first_name }} is involved:</h5>
                                        {% for task in user_view.user.task_set.all %}
                                        <li>{{ task }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="card-body">
                                    <div class="tab-pane p-3 active show">
                                      <div class="message">
                                        <div class="py-3 pb-5 mr-3 float-left">
                                          <div class="avatar">
                                            <img src="{{ user_view.img.url }}" class="img-avatar" alt="{{ friend.user.get_full_name }}">
                                            <span class="avatar-status badge-success"></span>
                                          </div>
                                        </div>
                                        <div>
                                          <small class="text-muted">{{ user_view.user.get_full_name }}</small>
                                            {% if user_view.user.last_login %}
                                          <small class="text-muted float-right mt-1">Last login: {{ user_view.user.last_login|date:"H:i" }} in {{ user_view.user.last_login|date:"d/m" }}</small>
                                            {% endif %}
                                        </div>
                                        <div class="text-truncate font-weight-bold">{{ user_view.company }}</div>
                                        {% if user_view.user.project_set %}
                                        <em class="text-muted">Projects that {{ user_view.user.first_name }} is working:</em>
                                        <small class="text-muted">
                                            {% for project in user_view.user.project_set.all %}
                                            {{ project }},
                                            {% endfor %}
                                        </small>
                                        {% else %}
                                        <em class="text-muted">{{ user_view.user.first_name }} is working in no projects until now.</em>
                                        {% endif %}
                                      </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="card-body">
                                    <div class="tab-pane p-3 active show">
                                        {% if user_view.friends.all %}
                                        <h5 class="">{{ user_view.user.first_name }}'s Friends:</h5>
                                        <div class="row">
                                        {% for friend in user_view.friends.all %}
                                        <div class="py-3 pb-5 mr-3 float-left ml-3" style="width: 20%">
                                            <p class="avatar">
                                                <img src="{{ friend.img.url }}" class="img-avatar" alt="{{ friend.user.get_full_name }}">
                                                <span class="avatar-status badge-success"></span>
                                            </p>
                                            <p>
                                                <a href="{% url 'register:user' profile_id=friend.id%}" class="text-info">{{ friend.user.first_name }}</a>
                                            </p>
                                        </div>
                                        {% endfor%}
                                        {% else %}
                                        <em class="text-muted">{{ user_view.user.first_name }} have no friends.</em>
                                        {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}